export const CURRENT_PROJECT_SCHEMA_VERSION = 2;
export const VLO_APP_VERSION = import.meta.env.VITE_APP_VERSION;

export const PROJECT_MANIFEST_SCHEMA_VERSION = 3;
export const TIMELINE_DOCUMENT_SCHEMA_VERSION = 1;
export const ASSET_INDEX_DOCUMENT_SCHEMA_VERSION = 1;
export const ASSET_METADATA_DOCUMENT_SCHEMA_VERSION = 1;
