// This file is generated by scripts/generate_workflow_rules_types.py.

// Do not edit it manually.

export interface AspectRatioTargetNode {
  node_id: string;
  width_param: string;
  height_param: string;
}

export interface NodeOutputSource {
  kind?: "node_output";
  node_id: string;
  output_index?: number;
}

export interface ResolvedOutputInjectionRule {
  source: NodeOutputSource;
}

export interface WorkflowRuleNode {
  ignore?: boolean;
  present?: WorkflowRuleNodePresent | null;
  widgets_mode?: "control_after_generate" | "all" | null;
  widgets?: Record<string, WorkflowRuleWidgetEntry>;
  selection?: WorkflowRuleSelectionConfig | null;
  binary_derived_mask_of?: string | null;
  soft_derived_mask_of?: string | null;
  node_title?: string | null;
}

export interface WorkflowAspectRatioPostprocessConfig {
  enabled?: boolean;
  mode?: "stretch_exact";
  apply_to?: "all_visual_outputs";
}

export interface WorkflowAspectRatioProcessingConfig {
  enabled?: boolean;
  stride?: number;
  search_steps?: number;
  resolutions?: Array<number>;
  target_nodes?: Array<AspectRatioTargetNode>;
  postprocess?: WorkflowAspectRatioPostprocessConfig;
}

export interface WorkflowAtLeastNInputValidationRule {
  kind: "at_least_n";
  inputs?: Array<string>;
  min: number;
  message?: string | null;
}

export interface WorkflowDualSamplerDenoiseRule {
  id: string;
  kind?: "dual_sampler_denoise";
  label?: string | null;
  group_id?: string | null;
  group_title?: string | null;
  group_order?: number | null;
  total_steps: WorkflowParamReference;
  start_step: WorkflowParamReference;
  base_split_step: WorkflowParamReference;
  split_step_targets?: Array<WorkflowParamReference>;
}

export interface WorkflowInputCondition {
  kind?: "at_least_one";
  inputs?: Array<string>;
  message?: string | null;
}

export interface WorkflowMaskCroppingConfig {
  mode?: "crop" | "full";
}

export interface WorkflowOptionalInputValidationRule {
  kind: "optional";
  input: string;
  message?: string | null;
}

export interface WorkflowParamReference {
  node_id: string;
  param: string;
}

export interface WorkflowPostprocessingConfig {
  mode?: "auto" | "stitch_frames_with_audio" | "none";
  panel_preview?: "raw_outputs" | "replace_outputs";
  on_failure?: "fallback_raw" | "show_error";
  stitch_fps?: number | null;
}

export interface WorkflowRequiredInputValidationRule {
  kind: "required";
  input: string;
  message?: string | null;
}

export interface WorkflowRuleNodePresent {
  enabled?: boolean | null;
  required?: boolean | null;
  input_type?: string | null;
  param?: string | null;
  label?: string | null;
  class_type?: string | null;
}

export interface WorkflowRuleSelectionConfig {
  export_fps?: number | null;
  frame_step?: number | null;
  max_frames?: number | null;
}

export interface WorkflowRuleSlot {
  input_type?: string | null;
  label?: string | null;
  param?: string | null;
  experimental?: boolean | null;
  export_fps?: number | null;
  frame_step?: number | null;
  max_frames?: number | null;
}

export interface WorkflowRuleWidgetEntry {
  label?: string | null;
  control_after_generate?: boolean;
  default_randomize?: boolean | null;
  frontend_only?: boolean | null;
  hidden?: boolean | null;
  group_id?: string | null;
  group_title?: string | null;
  group_order?: number | null;
  min?: number | null;
  max?: number | null;
  default?: unknown | null;
  value_type?: "int" | "float" | "string" | "boolean" | "enum" | "unknown" | null;
  options?: Array<string | number | boolean> | null;
}

export interface WorkflowValidationConfig {
  inputs?: Array<WorkflowRequiredInputValidationRule | WorkflowAtLeastNInputValidationRule | WorkflowOptionalInputValidationRule>;
}

export interface WorkflowRules {
  version?: number;
  name?: string | null;
  nodes?: Record<string, WorkflowRuleNode>;
  validation?: WorkflowValidationConfig;
  input_conditions?: Array<WorkflowInputCondition> | null;
  derived_widgets?: Array<WorkflowDualSamplerDenoiseRule>;
  output_injections?: Record<string, Record<string, ResolvedOutputInjectionRule>>;
  slots?: Record<string, WorkflowRuleSlot>;
  mask_cropping?: WorkflowMaskCroppingConfig;
  postprocessing?: WorkflowPostprocessingConfig;
  aspect_ratio_processing?: WorkflowAspectRatioProcessingConfig;
}
