// This file is generated by scripts/generate_workflow_rules_types.py.

// Do not edit it manually.

export interface AspectRatioTargetNode {
  width: WorkflowParamReference;
  height: WorkflowParamReference;
}

export interface ConditionAllOf {
  kind?: "all_of";
  conditions?: Array<ConditionAlways | WorkflowRuleWidgetInputPresenceCondition | ConditionCompare | ConditionAllOf | ConditionAnyOf | ConditionNot>;
}

export interface ConditionAlways {
  kind?: "always";
  value?: boolean;
}

export interface ConditionAnyOf {
  kind?: "any_of";
  conditions?: Array<ConditionAlways | WorkflowRuleWidgetInputPresenceCondition | ConditionCompare | ConditionAllOf | ConditionAnyOf | ConditionNot>;
}

export interface ConditionCompare {
  kind?: "compare";
  ref: WorkflowParamValueReference | PipelineControlReference | FrontendControlStateReference | DerivedWidgetStateReference;
  operator?: "eq" | "neq" | "lt" | "lte" | "gt" | "gte";
  value?: unknown | null;
}

export interface ConditionNot {
  kind?: "not";
  condition: ConditionAlways | WorkflowRuleWidgetInputPresenceCondition | ConditionCompare | ConditionAllOf | ConditionAnyOf | ConditionNot;
}

export interface DerivedWidgetStateReference {
  kind?: "derived_widget";
  derived_widget_id: string;
}

export interface EffectSwitch {
  id?: string | null;
  cases?: Array<EffectSwitchCase>;
}

export interface EffectSwitchCase {
  when: ConditionAlways | WorkflowRuleWidgetInputPresenceCondition | ConditionCompare | ConditionAllOf | ConditionAnyOf | ConditionNot;
  bypass?: Array<string>;
  set_widgets?: Array<WorkflowRewriteWidgetOverride>;
}

export interface FrontendControlStateReference {
  kind?: "frontend_control";
  control_id: string;
}

export interface MaskProcessingTarget {
  source: WorkflowParamReference;
  mask: WorkflowParamReference;
  mask_type?: "binary" | "soft";
  purpose?: "video" | "audio_timing";
  render_fps?: number | null;
}

export interface PipelineControl {
  key: string;
  label?: string | null;
  description?: string | null;
  value_type?: "int" | "float" | "string" | "boolean" | "enum" | "unknown";
  expose?: "widget" | "none";
  source?: "client" | "backend" | null;
  control?: "slider" | null;
  slider_display?: "percent" | "number" | null;
  unit?: string | null;
  min?: number | null;
  max?: number | null;
  step?: number | null;
  default?: unknown | null;
  options?: Array<string | number | boolean> | null;
  include_options?: Array<string | number | boolean> | null;
  exclude_options?: Array<string | number | boolean> | null;
  true_value?: unknown | null;
  false_value?: unknown | null;
  bind?: WorkflowParamValueReference | PipelineControlReference | FrontendControlStateReference | DerivedWidgetStateReference | null;
  default_rules?: Array<PipelineControlDefaultRule> | null;
}

export interface PipelineControlCondition {
  ref: WorkflowParamValueReference | PipelineControlReference | FrontendControlStateReference | DerivedWidgetStateReference;
  operator?: "eq" | "neq" | "lt" | "lte" | "gt" | "gte";
  value?: unknown | null;
}

export interface PipelineControlDefaultRule {
  when: PipelineControlCondition;
  value?: unknown | null;
}

export interface PipelineControlReference {
  kind?: "pipeline_control";
  stage_id: string;
  key: string;
}

export interface WorkflowAspectRatioPostprocessConfig {
  enabled?: boolean;
  mode?: "stretch_exact";
  apply_to?: "all_visual_outputs";
}

export interface WorkflowAspectRatioStage {
  id: string;
  enabled?: boolean;
  label?: string | null;
  description?: string | null;
  after?: Array<string>;
  controls?: Array<PipelineControl>;
  kind?: "aspect_ratio";
  config?: WorkflowAspectRatioStageConfig;
  targets?: Array<AspectRatioTargetNode>;
}

export interface WorkflowAspectRatioStageConfig {
  stride?: number;
  search_steps?: number;
  resolutions?: Array<number>;
  postprocess?: WorkflowAspectRatioPostprocessConfig;
}

export interface WorkflowAtLeastNInputValidationRule {
  kind: "at_least_n";
  inputs?: Array<string>;
  min: number;
  message?: string | null;
}

export interface WorkflowConditionalBooleanOverride {
  when: ConditionAlways | WorkflowRuleWidgetInputPresenceCondition | ConditionCompare | ConditionAllOf | ConditionAnyOf | ConditionNot;
  value?: boolean;
}

export interface WorkflowDualSamplerDenoiseRule {
  id: string;
  kind?: "dual_sampler_denoise";
  label?: string | null;
  when?: ConditionAlways | WorkflowRuleWidgetInputPresenceCondition | ConditionCompare | ConditionAllOf | ConditionAnyOf | ConditionNot | null;
  group_id?: string | null;
  group_title?: string | null;
  group_order?: number | null;
  total_steps: WorkflowParamReference;
  start_step: WorkflowParamReference;
  base_split_step: WorkflowParamReference;
  split_step_targets?: Array<WorkflowParamReference>;
}

export interface WorkflowFrontendControl {
  label?: string | null;
  when?: ConditionAlways | WorkflowRuleWidgetInputPresenceCondition | ConditionCompare | ConditionAllOf | ConditionAnyOf | ConditionNot | null;
  control_after_generate?: boolean;
  default_randomize?: boolean | null;
  frontend_only?: boolean | null;
  hidden?: boolean | null;
  control?: "slider" | null;
  slider_display?: "percent" | "number" | null;
  unit?: string | null;
  group_id?: string | null;
  group_title?: string | null;
  group_order?: number | null;
  min?: number | null;
  max?: number | null;
  step?: number | null;
  default?: unknown | null;
  value_type?: "int" | "float" | "string" | "boolean" | "enum" | "unknown" | null;
  options?: Array<string | number | boolean> | null;
  true_value?: unknown | null;
  false_value?: unknown | null;
  default_overrides?: Array<WorkflowRuleWidgetDefaultOverride> | null;
}

export interface WorkflowInputCondition {
  kind?: "at_least_one";
  inputs?: Array<string>;
  message?: string | null;
}

export interface WorkflowMaskProcessingStage {
  id: string;
  enabled?: boolean;
  label?: string | null;
  description?: string | null;
  after?: Array<string>;
  controls?: Array<PipelineControl>;
  kind?: "mask_processing";
  targets?: Array<MaskProcessingTarget>;
}

export interface WorkflowMediaFallback {
  kind?: "dummy";
  node_id: string;
  input_type: string;
  param?: string | null;
  filename?: string | null;
  content_type?: string | null;
  synthetic?: boolean;
  when?: WorkflowRuleWidgetInputPresenceCondition | null;
}

export interface WorkflowOptionalInputValidationRule {
  kind: "optional";
  input: string;
  message?: string | null;
}

export interface WorkflowOutputAssemblyStage {
  id: string;
  enabled?: boolean;
  label?: string | null;
  description?: string | null;
  after?: Array<string>;
  controls?: Array<PipelineControl>;
  kind?: "output_assembly";
  config?: WorkflowOutputAssemblyStageConfig;
}

export interface WorkflowOutputAssemblyStageConfig {
  mode?: "auto" | "stitch_frames_with_audio" | "none";
  panel_preview?: "raw_outputs" | "replace_outputs";
  on_failure?: "fallback_raw" | "show_error";
  stitch_fps?: number | null;
}

export interface WorkflowParamReference {
  node_id: string;
  param: string;
}

export interface WorkflowParamValueReference {
  kind?: "workflow_param";
  node_id: string;
  param: string;
}

export interface WorkflowRequiredInputValidationRule {
  kind: "required";
  input: string;
  message?: string | null;
}

export interface WorkflowRewriteRule {
  when: ConditionAlways | WorkflowRuleWidgetInputPresenceCondition | ConditionCompare | ConditionAllOf | ConditionAnyOf | ConditionNot;
  bypass?: Array<string>;
  set_widgets?: Array<WorkflowRewriteWidgetOverride>;
}

export interface WorkflowRewriteWidgetOverride {
  node_id: string;
  widget: string;
  value?: unknown | null;
}

export interface WorkflowRuleNode {
  ignore?: boolean;
  ignore_overrides?: Array<WorkflowConditionalBooleanOverride> | null;
  present?: WorkflowRuleNodePresent | null;
  widgets_mode?: "control_after_generate" | "all" | null;
  widgets?: Record<string, WorkflowRuleWidgetEntry>;
  selection?: WorkflowRuleSelectionConfig | null;
  node_title?: string | null;
}

export interface WorkflowRuleNodePresent {
  enabled?: boolean | null;
  required?: boolean | null;
  input_type?: string | null;
  param?: string | null;
  label?: string | null;
  class_type?: string | null;
  group_id?: string | null;
  group_title?: string | null;
  group_order?: number | null;
}

export interface WorkflowRuleSelectionConfig {
  export_fps?: number | null;
  frame_step?: number | null;
  max_frames?: number | null;
}

export interface WorkflowRuleSlot {
  input_type?: string | null;
  label?: string | null;
  param?: string | null;
  experimental?: boolean | null;
  export_fps?: number | null;
  frame_step?: number | null;
  max_frames?: number | null;
}

export interface WorkflowRuleWidgetDefaultOverride {
  when: ConditionAlways | WorkflowRuleWidgetInputPresenceCondition | ConditionCompare | ConditionAllOf | ConditionAnyOf | ConditionNot;
  value?: unknown | null;
}

export interface WorkflowRuleWidgetEntry {
  label?: string | null;
  when?: ConditionAlways | WorkflowRuleWidgetInputPresenceCondition | ConditionCompare | ConditionAllOf | ConditionAnyOf | ConditionNot | null;
  control_after_generate?: boolean;
  default_randomize?: boolean | null;
  frontend_only?: boolean | null;
  hidden?: boolean | null;
  control?: "slider" | null;
  slider_display?: "percent" | "number" | null;
  unit?: string | null;
  group_id?: string | null;
  group_title?: string | null;
  group_order?: number | null;
  min?: number | null;
  max?: number | null;
  step?: number | null;
  default?: unknown | null;
  value_type?: "int" | "float" | "string" | "boolean" | "enum" | "unknown" | null;
  options?: Array<string | number | boolean> | null;
  true_value?: unknown | null;
  false_value?: unknown | null;
  default_overrides?: Array<WorkflowRuleWidgetDefaultOverride> | null;
}

export interface WorkflowRuleWidgetInputPresenceCondition {
  kind?: "input_presence";
  inputs?: Array<string>;
  match?: "all_present" | "all_missing" | "any_present" | "any_missing";
}

export interface WorkflowSingleSamplerDenoiseRule {
  id: string;
  kind?: "single_sampler_denoise";
  label?: string | null;
  when?: ConditionAlways | WorkflowRuleWidgetInputPresenceCondition | ConditionCompare | ConditionAllOf | ConditionAnyOf | ConditionNot | null;
  group_id?: string | null;
  group_title?: string | null;
  group_order?: number | null;
  total_steps: WorkflowParamReference;
  start_step: WorkflowParamReference;
}

export interface WorkflowValidationConfig {
  inputs?: Array<WorkflowRequiredInputValidationRule | WorkflowAtLeastNInputValidationRule | WorkflowOptionalInputValidationRule>;
}

export interface WorkflowVideoAudioRetakeRule {
  id: string;
  kind?: "video_audio_retake";
  label?: string | null;
  when?: ConditionAlways | WorkflowRuleWidgetInputPresenceCondition | ConditionCompare | ConditionAllOf | ConditionAnyOf | ConditionNot | null;
  group_id?: string | null;
  group_title?: string | null;
  group_order?: number | null;
  default?: "Video & Audio" | "Video" | "Audio";
  video_bypass: WorkflowParamReference;
  audio_bypass: WorkflowParamReference;
}

export interface WorkflowRules {
  version?: 3;
  name?: string | null;
  default_widgets_mode?: "control_after_generate" | "all" | null;
  nodes?: Record<string, WorkflowRuleNode>;
  validation?: WorkflowValidationConfig;
  input_conditions?: Array<WorkflowInputCondition> | null;
  frontend_controls?: Record<string, WorkflowFrontendControl>;
  derived_widgets?: Array<WorkflowDualSamplerDenoiseRule | WorkflowSingleSamplerDenoiseRule | WorkflowVideoAudioRetakeRule>;
  rewrites?: Array<WorkflowRewriteRule>;
  effect_switches?: Array<EffectSwitch>;
  slots?: Record<string, WorkflowRuleSlot>;
  media_fallbacks?: Array<WorkflowMediaFallback>;
  pipeline?: Array<WorkflowMaskProcessingStage | WorkflowAspectRatioStage | WorkflowOutputAssemblyStage>;
}
